services:

  db:
    image: postgres:alpine
    container_name: db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      PGOPTIONS: "-c log_statement=all -c log_min_duration_statement=0 -c logging_collector=on -c log_destination=stderr"
    ports:
      - "5432:5432"
  gotenberg:
    image: gotenberg/gotenberg
    ports:
      - "3000:3000"
    command:
      - "gotenberg"
      - "--api-timeout=120s"
      - "--log-level=info"